sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: aiwj2MGX19EMru12D9P3360+IBpLy6py+4fm4dimYiXmKZ6K60iD0EV+EhzDX6C+7pP8E33a/zCw9EXS7PZKSVxfyjjcNH9pXq+wpQQpwPpM+qAPU0ykRcSAk8HvkWaaSka9dcG+dDIYx3MnVGK85Omy5NYiVTKrPRXVbWTl4a1c7FilSr7EZftyrMEgTNr9tc35wkmK9i/rb3b7ziCSpcTYYGchBj68XIBMXE9DF5mmd6wcrKnPc5unGgEdEZrRHJEBrAk14AcEPv3ZA+XCufeorx2MOrUQHzVrYYroewGE1EGBXgyKxGAWgTCM3BWTJQRNoF/Z1BSU6fVfXfBj/vKdYyTFw05xDBtA3d0Of3xF5dy4+SWmQJMipCz6toS7yb/LqGEnxa3egigH9cdsuTPOvulyz0AxXXR/I3aJDaXXndKTAwWyDW7er/f2vXzNyK+l3YNEJnpeyrsUxlHMOJjcYJEiUf0oQYph6FwYn1c4XvA7qxDGeAZtYF4yZ4FTQpNHiPKj5uVCnfEkVQ1barLj2N6EHefHs3CVeAOJtOCPILzW9ymz5cPdqRIDEZZsQ+bB6KkvxzDIy+MT5CEXt4Z3uSdVyI8lGaaiDv+jz1Dbdb6A6f38gIn+r1EPc3KUCnZKLA8s3ppvPCwQq08LkquJ40E6q9IFTMCE1BCjCgE=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: h4B/npM7JjCSNF41Szhs2Y/QIqWpU4f+48SnjwSobgGGTFOh67vNI7ZWBRXztUHH7X4zHtpqHv8glkeqdtMatQtWbwiFI+JlBfj1GXqIU/P3V7o7DZrVaGzc6/qTha2r+uR3HphSWDtNO6OkKCDAelgfOx/kZxbzmJSkZvvnve87eApVKy8TXbL4Mbu+EgwT2L9gT0J4t9k0Ro4bBS+3fyVWYMJSz2FDFgLuwNijaW112TfnD0pBcojTax/lrzMoPuuU8fiWy5kfM3XL98G69nZy6IcH58vnI2XhbvsYMzFgEFxunX6vyuW3UDJ41rlrf4dIjVm75tXlVSjavXX8OjZAe28CEtYyhtzjea5DBPjpcGO/mEk58f1S+P9viBPMCjnuUccKzTanTf1qIS/kyneVLWh5AG6t/ahouRPUITlfHKl0wNEhG2vHb3oUVMCaMpVKLh2At8nWh5puNJLFc92PfXY3/B+k4KGF/mnLODDGCTtoco/OadnZ+BJ9glc4+Bu6h2qaCmLxZgJS27kj+BF+LWOszYJXQ/Gq188K4CAvFugYUFWXHLh2RNdJ1FB2pH07sTSi45sW+8xaaX/Gtdr7/APU7VcAZD/j4No/JTFnWiL6XJj3DERmG5TSJT7+545Ka7IH3c89dXElg6BMn9PS5g6fT5uh97/J5OOhg6o=
